rsa.private = """-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQEAzLf42lFlgubf24evaDTXyx6D29z+kgzIAVq38eVrQM/bdT1r
wC5v3Zkij+CGuEEsVdHedS+Cja9h68Gp3WLoGSnJrMGe3haO+onsNWy5V2z4ewnS
4a8KOwYEzwQwau57tb5Zxth3gMfyKiGxgwGzW4ZV3mjdUVl5z72ymbOs6jHcQDjd
Iq0xXBg0NEpZafa5598S6J1zTaBdfc5QEsBIZPjuUibfUFd3thO2ihNTFnmzScKa
1XIdLHmgtYDSBWhmxpEAwRqfBQlURlbuBKvSHk8YEVBSDNdPWCrzjWk2kCk7oQWy
yLNO65cm9dr1RU/zRcs/GW3D6IH2ZnFqAbkY1wIDAQABAoIBAQCM0ew7eQxD3D6W
iyJMozThgu8fGUh//IzD6bxoh/CcF58VaZeqDgdjPoh4wfDJ5AL0UbYdk/3RKphI
DOKk5/lR/d29mT6H9KqLir5SDaT8j3fpYtuN5NM7wKskH/SSSdQNM5Ab6SFjE6bv
9ldeD5hp1+FPaYD8CXlyPkIR2neSbFjFoZgUADOLWQtQxm1BYpYN34fk1jYbJPyG
mhYQ0hEkLGq1GeAJB5zgEl7CL90wJV6HxjPlGNigXG1I4kcORP+TnORz8Ba8gSr0
BGdm+Cgr+jehqwm5evrKkrpSCRLjTN4FItqdftQ5T2pFzDWhmupBBIB9F4kJYjWL
wWC9AkJxAoGBAOwA9gd2ogUABb0b8DJOFau0Wzi4EhvAF612473bYWeWug8JkztV
/sx7YXcOm1xM0vVw2SEgn/9M4mWNnSXz5SbALAsiaZqQNzWNDTvm3QDCBpaUpUk+
MKBhQy0IeKOSQsmK4fGuL+ReMMQby9Gz0yOmI+tleFm9yE9vwE+MmllfAoGBAN4Q
a91bipC+d/77IZZfQeWf4idQsM3zeJ5s7KVQbgjj1qEsSERN5JYJzTMsaBtnWEIx
il2EBoPsbg6cT2h9ObCEEmziXG99ezYKEhCuYL3hw4ZmUZlNvFWs91dfQP1/rox4
NI2f3OtWilcUJi+rrKkIJHnqwfWnB6NC59fINduJAoGBAMKhiEVfcP7upczv3Yef
HgAdHZ4JL+Xy5ZQJGIjbA9mKVKdSHjoxEZFRr2+gfEACm3gPOQI5Bbpmjc9ymsdR
/QmYMrp8BtuRU/a1/NQJ8PlPCl/k9usQfsnFbMEW22cKmEneX7gRDy4m/9C7m7u1
scsUmUrow/g+q5PXdaIlMqXBAoGBAJNakjjw5aHmwfmQ61i9HR0iWw97m9cOGJwH
64BHPrzncyTAHbQ1e9mT53ZtoSeODCLgfNBRK4GfAejwEEFl10IqYY+fJXdV7MyP
Ii2viMJ3bSdh/gOccbzoabiwnI+ailjr6vOPgSko4+OkmzJG2OvRW2MLRGmdzJOp
ce7eC98BAoGBAOSWBYWPXhdGe6bl7H/VtzLzGg0HJXqoCPVNTD46qs3A2JkZ1Hdp
GYRlN2z7s0Fr7JKhpepXaZZew4l+XuOM4t006jXXIrGML/AnYCPeDfFJYTiTGQwY
KsHwYflhVJCNQRJWtaPaLNXblWsv2RO1AWPWaHlmGoyHTSa0FVltpHvv
-----END RSA PRIVATE KEY-----"""

	rsa.public = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzLf42lFlgubf24evaDTX
yx6D29z+kgzIAVq38eVrQM/bdT1rwC5v3Zkij+CGuEEsVdHedS+Cja9h68Gp3WLo
GSnJrMGe3haO+onsNWy5V2z4ewnS4a8KOwYEzwQwau57tb5Zxth3gMfyKiGxgwGz
W4ZV3mjdUVl5z72ymbOs6jHcQDjdIq0xXBg0NEpZafa5598S6J1zTaBdfc5QEsBI
ZPjuUibfUFd3thO2ihNTFnmzScKa1XIdLHmgtYDSBWhmxpEAwRqfBQlURlbuBKvS
Hk8YEVBSDNdPWCrzjWk2kCk7oQWyyLNO65cm9dr1RU/zRcs/GW3D6IH2ZnFqAbkY
1wIDAQAB
-----END PUBLIC KEY-----"""
